
import { Parable } from './types';

export const PARABLES: Parable[] = [
  { id: 'salt-light', title: 'Salt of the Earth & Light of the World', reference: 'Matthew 5:13-16', order: 1, gospels: ['Matthew'], shortDescription: 'The influence and witness of the believer in the world.' },
  { id: 'speck-plank', title: 'The Speck and the Plank', reference: 'Matthew 7:3-5', order: 2, gospels: ['Matthew', 'Luke'], shortDescription: 'The danger of hypocrisy and judgmentalism.' },
  { id: 'wise-foolish-builders', title: 'The Wise and Foolish Builders', reference: 'Matthew 7:24-27', order: 3, gospels: ['Matthew', 'Luke'], shortDescription: 'Building life on the solid foundation of God\'s Word.' },
  { id: 'physician', title: 'The Physician', reference: 'Matthew 9:12', order: 4, gospels: ['Matthew', 'Mark', 'Luke'], shortDescription: 'Jesus\' mission to the spiritually sick.' },
  { id: 'new-cloth', title: 'New Cloth on an Old Garment', reference: 'Matthew 9:16', order: 5, gospels: ['Matthew', 'Mark', 'Luke'], shortDescription: 'The incompatibility of the New Covenant with old legalism.' },
  { id: 'new-wine', title: 'New Wine in Old Wineskins', reference: 'Matthew 9:17', order: 6, gospels: ['Matthew', 'Mark', 'Luke'], shortDescription: 'The freshness and power of the Gospel requires new hearts.' },
  { id: 'children-market', title: 'Children in the Marketplace', reference: 'Matthew 11:16-19', order: 7, gospels: ['Matthew', 'Luke'], shortDescription: 'The fickle response of a generation to God\'s messengers.' },
  { id: 'sower', title: 'The Sower', reference: 'Matthew 13:3-9', order: 8, gospels: ['Matthew', 'Mark', 'Luke'], shortDescription: 'Four ways that human hearts receive the Word of God.' },
  { id: 'lamp-stand', title: 'The Lamp on a Stand', reference: 'Mark 4:21-25', order: 9, gospels: ['Matthew', 'Mark', 'Luke'], shortDescription: 'Truth is meant to be revealed and shared, not hidden.' },
  { id: 'growing-seed', title: 'The Growing Seed', reference: 'Mark 4:26-29', order: 10, gospels: ['Mark'], shortDescription: 'The mysterious, unstoppable growth of God\'s Kingdom.' },
  { id: 'mustard-seed', title: 'The Mustard Seed', reference: 'Matthew 13:31-32', order: 11, gospels: ['Matthew', 'Mark', 'Luke'], shortDescription: 'The Kingdom starts small but grows into a place of refuge.' },
  { id: 'yeast', title: 'The Yeast (Leaven)', reference: 'Matthew 13:33', order: 12, gospels: ['Matthew', 'Luke'], shortDescription: 'The pervasive, inward transformation of the Kingdom.' },
  { id: 'weeds', title: 'The Weeds (Wheat & Tares)', reference: 'Matthew 13:24-30', order: 13, gospels: ['Matthew'], shortDescription: 'Good and evil coexist until the final harvest.' },
  { id: 'hidden-treasure', title: 'The Hidden Treasure', reference: 'Matthew 13:44', order: 14, gospels: ['Matthew'], shortDescription: 'The joy of discovering the supreme value of the Kingdom.' },
  { id: 'pearl', title: 'The Pearl of Great Price', reference: 'Matthew 13:45-46', order: 15, gospels: ['Matthew'], shortDescription: 'Sacrificing everything for the one thing that truly matters.' },
  { id: 'net', title: 'The Net', reference: 'Matthew 13:47-50', order: 16, gospels: ['Matthew'], shortDescription: 'The gathering and final sorting of all people.' },
  { id: 'scribe-house', title: 'The Scribe as Householder', reference: 'Matthew 13:52', order: 17, gospels: ['Matthew'], shortDescription: 'Bringing out both old and new treasures of truth.' },
  { id: 'two-debtors', title: 'The Two Debtors', reference: 'Luke 7:41-43', order: 18, gospels: ['Luke'], shortDescription: 'Gratitude and love are proportional to forgiven debt.' },
  { id: 'strong-man', title: 'The Strong Man', reference: 'Matthew 12:29', order: 19, gospels: ['Matthew', 'Mark', 'Luke'], shortDescription: 'Jesus binding Satan to set the captives free.' },
  { id: 'return-spirit', title: 'The Return of the Unclean Spirit', reference: 'Matthew 12:43-45', order: 20, gospels: ['Matthew', 'Luke'], shortDescription: 'The danger of a "clean" but empty spiritual life.' },
  { id: 'unforgiving-servant', title: 'The Unforgiving Servant', reference: 'Matthew 18:23-35', order: 21, gospels: ['Matthew'], shortDescription: 'The command to forgive as we have been forgiven.' },
  { id: 'good-samaritan', title: 'The Good Samaritan', reference: 'Luke 10:25-37', order: 22, gospels: ['Luke'], shortDescription: 'Defining "neighbor" through mercy, not proximity.' },
  { id: 'friend-midnight', title: 'The Friend at Midnight', reference: 'Luke 11:5-8', order: 23, gospels: ['Luke'], shortDescription: 'Persistence and boldness in approaching God in prayer.' },
  { id: 'rich-fool', title: 'The Rich Fool', reference: 'Luke 12:16-21', order: 24, gospels: ['Luke'], shortDescription: 'The futility of hoarding earthly wealth.' },
  { id: 'watchful-servants', title: 'The Watchful Servants', reference: 'Luke 12:35-40', order: 25, gospels: ['Luke'], shortDescription: 'Being ready for the Master\'s return at any hour.' },
  { id: 'wise-manager', title: 'The Wise and Faithful Manager', reference: 'Luke 12:42-48', order: 26, gospels: ['Luke'], shortDescription: 'Accountability for what God has entrusted to us.' },
  { id: 'barren-fig-tree', title: 'The Barren Fig Tree', reference: 'Luke 13:6-9', order: 27, gospels: ['Luke'], shortDescription: 'A period of grace before the final call for fruit.' },
  { id: 'lowest-seat', title: 'The Lowest Seat', reference: 'Luke 14:7-11', order: 28, gospels: ['Luke'], shortDescription: 'The blessing of humility over self-promotion.' },
  { id: 'great-banquet', title: 'The Great Banquet', reference: 'Luke 14:15-24', order: 29, gospels: ['Luke'], shortDescription: 'God\'s invitation is wide, but excuses can lead to exclusion.' },
  { id: 'cost-discipleship', title: 'Counting the Cost', reference: 'Luke 14:28-33', order: 30, gospels: ['Luke'], shortDescription: 'The serious commitment required to follow Jesus.' },
  { id: 'lost-sheep', title: 'The Lost Sheep', reference: 'Luke 15:3-7', order: 31, gospels: ['Matthew', 'Luke'], shortDescription: 'The Father\'s pursuit of the one who wandered away.' },
  { id: 'lost-coin', title: 'The Lost Coin', reference: 'Luke 15:8-10', order: 32, gospels: ['Luke'], shortDescription: 'God\'s diligent search for those who are lost.' },
  { id: 'prodigal-son', title: 'The Prodigal Son', reference: 'Luke 15:11-32', order: 33, gospels: ['Luke'], shortDescription: 'The radical grace and joy of the Father.' },
  { id: 'shrewd-manager', title: 'The Shrewd Manager', reference: 'Luke 16:1-13', order: 34, gospels: ['Luke'], shortDescription: 'Using earthly resources for eternal gain.' },
  { id: 'rich-man-lazarus', title: 'The Rich Man and Lazarus', reference: 'Luke 16:19-31', order: 35, gospels: ['Luke'], shortDescription: 'The great reversal of status in the afterlife.' },
  { id: 'unworthy-servants', title: 'The Unworthy Servants', reference: 'Luke 17:7-10', order: 36, gospels: ['Luke'], shortDescription: 'Duty and service as the standard, not a source of pride.' },
  { id: 'persistent-widow', title: 'The Persistent Widow', reference: 'Luke 18:1-8', order: 37, gospels: ['Luke'], shortDescription: 'Justice will come for those who never stop praying.' },
  { id: 'pharisee-tax-collector', title: 'The Pharisee and the Tax Collector', reference: 'Luke 18:9-14', order: 38, gospels: ['Luke'], shortDescription: 'Righteousness through humility, not religious performance.' },
  { id: 'workers-vineyard', title: 'The Workers in the Vineyard', reference: 'Matthew 20:1-16', order: 39, gospels: ['Matthew'], shortDescription: 'God\'s grace is not based on "fairness" by human standards.' },
  { id: 'ten-minas', title: 'The Ten Minas', reference: 'Luke 19:11-27', order: 40, gospels: ['Luke'], shortDescription: 'Faithfulness while waiting for the King\'s return.' },
  { id: 'two-sons', title: 'The Two Sons', reference: 'Matthew 21:28-32', order: 41, gospels: ['Matthew'], shortDescription: 'Action matters more than words in the Kingdom.' },
  { id: 'wicked-tenants', title: 'The Wicked Tenants', reference: 'Matthew 21:33-46', order: 42, gospels: ['Matthew', 'Mark', 'Luke'], shortDescription: 'The rejection and judgment of the Son.' },
  { id: 'wedding-banquet', title: 'The Wedding Banquet', reference: 'Matthew 22:1-14', order: 43, gospels: ['Matthew'], shortDescription: 'The requirement of the wedding garment of righteousness.' },
  { id: 'fig-tree-lesson', title: 'The Lesson of the Fig Tree', reference: 'Matthew 24:32-35', order: 44, gospels: ['Matthew', 'Mark', 'Luke'], shortDescription: 'Recognizing the signs of the end times.' },
  { id: 'thief-night', title: 'The Thief in the Night', reference: 'Matthew 24:42-44', order: 45, gospels: ['Matthew', 'Luke'], shortDescription: 'The suddenness and surprise of Christ\'s return.' },
  { id: 'ten-virgins', title: 'The Ten Virgins', reference: 'Matthew 25:1-13', order: 46, gospels: ['Matthew'], shortDescription: 'Spiritual readiness and the oil of the Spirit.' },
  { id: 'talents', title: 'The Talents', reference: 'Matthew 25:14-30', order: 47, gospels: ['Matthew'], shortDescription: 'Investing what we are given for God\'s glory.' },
  { id: 'sheep-goats', title: 'The Sheep and the Goats', reference: 'Matthew 25:31-46', order: 48, gospels: ['Matthew'], shortDescription: 'Judgment based on how we treated the "least of these".' },
  { id: 'door-shepherd', title: 'The Door and the Shepherd', reference: 'John 10:1-18', order: 49, gospels: ['John'], shortDescription: 'Jesus as the only way and the Good Shepherd.' },
  { id: 'vine-branches', title: 'The Vine and the Branches', reference: 'John 15:1-8', order: 50, gospels: ['John'], shortDescription: 'Abiding in Christ to bear fruit.' },
  { id: 'children-bride', title: 'The Children of the Bridechamber', reference: 'Mark 2:19-20', order: 51, gospels: ['Mark', 'Luke'], shortDescription: 'The time for celebration while the Groom is present.' },
  { id: 'divided-kingdom', title: 'The Divided Kingdom', reference: 'Mark 3:23-26', order: 52, gospels: ['Matthew', 'Mark', 'Luke'], shortDescription: 'A house divided against itself cannot stand.' },
  { id: 'blind-leading-blind', title: 'The Blind Leading the Blind', reference: 'Luke 6:39', order: 53, gospels: ['Matthew', 'Luke'], shortDescription: 'Choosing spiritual guides who can actually see.' },
  { id: 'tree-fruit', title: 'A Tree and its Fruit', reference: 'Luke 6:43-45', order: 54, gospels: ['Matthew', 'Luke'], shortDescription: 'Character reveals the heart\'s condition.' },
  { id: 'money-lender', title: 'The Money-lender and Two Debtors', reference: 'Luke 7:41-43', order: 55, gospels: ['Luke'], shortDescription: 'The connection between forgiveness and love.' },
];


  { id: 'tree-fruit', title: 'A Tree and its Fruit', reference: 'Luke 6:43-45', order: 54, gospels: ['Matthew', 'Luke'], shortDescription: 'Character reveals the heart\'s condition.' },
  { id: 'money-lender', title: 'The Money-lender and Two Debtors', reference: 'Luke 7:41-43', order: 55, gospels: ['Luke'], shortDescription: 'The connection between forgiveness and love.' },
];

